DROP TABLE IF EXISTS AdminPrivileges;

DROP TABLE IF EXISTS Admins;

DROP TABLE IF EXISTS UserPrivileges;

DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS RepoSettings;

DROP TABLE IF EXISTS Repositories;

DROP TABLE IF EXISTS AvailableTAs;

DROP TABLE IF EXISTS TAs;

DROP TABLE IF EXISTS GroupSettings;

DROP TABLE IF EXISTS Groups;
